// Mock flashcard and quiz data for demonstration
// In production, replace with actual OpenAI API calls

const FLASHCARD_TEMPLATES = {
  Biology: {
    'Photosynthesis': [
      { question: 'What is the equation for photosynthesis?', answer: '6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂', explanation: 'This is the overall equation where glucose and oxygen are produced from carbon dioxide and water using light energy.' },
      { question: 'Where does the light-dependent reaction occur?', answer: 'In the thylakoid membranes of the chloroplast', explanation: 'The light reactions require light energy and happen in the stacked structures called thylakoids.' },
      { question: 'What is the role of chlorophyll?', answer: 'To absorb light energy and convert it to chemical energy', explanation: 'Chlorophyll molecules in the thylakoid membranes capture photons and initiate the light reactions.' },
      { question: 'Name the products of the light-independent reaction.', answer: 'Glucose (and other organic compounds)', explanation: 'The Calvin cycle uses ATP and NADPH from light reactions to fix CO₂ into glucose.' },
      { question: 'What are the reactants needed for photosynthesis?', answer: 'Carbon dioxide and water', explanation: 'Along with light energy, these are the basic raw materials plants use to make glucose.' },
    ],
    'Cell Biology': [
      { question: 'What is the function of the mitochondria?', answer: 'To produce ATP through aerobic respiration', explanation: 'Mitochondria are the powerhouse of the cell, converting glucose into usable energy in the form of ATP.' },
      { question: 'What is the difference between prokaryotic and eukaryotic cells?', answer: 'Eukaryotic cells have a nucleus and organelles; prokaryotic cells lack these', explanation: 'Eukaryotic cells are more complex with membrane-bound organelles, while prokaryotic cells like bacteria are simpler.' },
      { question: 'What does the ribosome do?', answer: 'Synthesizes proteins from mRNA', explanation: 'Ribosomes read the genetic code on mRNA and assemble amino acids into proteins.' },
      { question: 'What is the role of the endoplasmic reticulum?', answer: 'To synthesize proteins (rough ER) and lipids (smooth ER)', explanation: 'The ER is a network of membranes involved in synthesis and transport of cellular products.' },
      { question: 'What is osmosis?', answer: 'The movement of water molecules across a semi-permeable membrane', explanation: 'Water moves from areas of high water potential to areas of low water potential.' },
    ],
  },
  Chemistry: {
    'Atomic Structure': [
      { question: 'What is the basic structure of an atom?', answer: 'A nucleus (protons and neutrons) surrounded by electron shells', explanation: 'The nucleus contains positively charged protons and neutral neutrons; electrons orbit in shells.' },
      { question: 'What is atomic number?', answer: 'The number of protons in an atom', explanation: 'Atomic number identifies the element and is unique for each element.' },
      { question: 'What is the difference between isotopes?', answer: 'Isotopes have the same atomic number but different mass numbers (different neutrons)', explanation: 'Isotopes are atoms of the same element with different numbers of neutrons.' },
    ],
  },
  Physics: {
    'Forces and Motion': [
      { question: 'What is Newton\'s First Law of Motion?', answer: 'An object in motion stays in motion unless acted upon by an external force', explanation: 'This is the law of inertia.' },
      { question: 'What is Newton\'s Second Law?', answer: 'Force equals mass times acceleration (F = ma)', explanation: 'The acceleration of an object is proportional to the net force and inversely proportional to its mass.' },
      { question: 'What is velocity?', answer: 'Speed in a specific direction', explanation: 'Velocity is a vector quantity, while speed is scalar.' },
    ],
  }
};

// Generate flashcards using mock data
export async function generateFlashcards(subject, topic, examBoard, count = 5) {
  try {
    const templates = FLASHCARD_TEMPLATES[subject]?.[topic] || [];
    
    if (templates.length === 0) {
      // Generate default flashcards if topic not found
      const defaultFlashcards = [];
      for (let i = 1; i <= count; i++) {
        defaultFlashcards.push({
          question: `${subject} - ${topic}: Question ${i}`,
          answer: `This is a sample answer for ${topic} question ${i}. In a production environment, this would be generated by AI.`,
          explanation: `This explanation provides context for the answer about ${topic}.`
        });
      }
      return defaultFlashcards;
    }

    // Return requested number of flashcards from templates
    return templates.slice(0, Math.min(count, templates.length));
  } catch (error) {
    console.error('Flashcard generation error:', error);
    throw new Error('Failed to generate flashcards');
  }
}

// Generate quiz using mock data
export async function generateQuiz(subject, topic, examBoard, count = 10) {
  try {
    const quizTemplates = {
      'Photosynthesis': [
        { question: 'What is the overall equation for photosynthesis?', options: { A: '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', B: 'C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂', C: '6O₂ + C₆H₁₂O₆ → 6CO₂ + 6H₂O', D: '2H₂O → 2H₂ + O₂' }, correctAnswer: 'A', marks: 1 },
        { question: 'Where does the light-dependent reaction occur?', options: { A: 'Stroma', B: 'Thylakoid membranes', C: 'Mitochondria', D: 'Ribosome' }, correctAnswer: 'B', marks: 1 },
        { question: 'What is the product of the light-independent reaction?', options: { A: 'Oxygen', B: 'ATP', C: 'Glucose', D: 'Chlorophyll' }, correctAnswer: 'C', marks: 1 },
      ],
      'Atomic Structure': [
        { question: 'What is the mass number of an atom with 6 protons and 7 neutrons?', options: { A: '6', B: '7', C: '13', D: '1' }, correctAnswer: 'C', marks: 1 },
        { question: 'Which subatomic particle has no charge?', options: { A: 'Proton', B: 'Electron', C: 'Neutron', D: 'Ion' }, correctAnswer: 'C', marks: 1 },
      ],
      'Forces and Motion': [
        { question: 'What does Newton\'s first law describe?', options: { A: 'F = ma', B: 'Inertia', C: 'Action and reaction', D: 'Gravity' }, correctAnswer: 'B', marks: 1 },
      ]
    };

    const template = quizTemplates[topic] || [];
    const questions = [];

    for (let i = 0; i < Math.min(count, Math.max(3, template.length)); i++) {
      const templateQ = template[i % template.length] || {
        question: `${subject} Question ${i + 1}`,
        options: { A: 'Option A', B: 'Option B', C: 'Option C', D: 'Option D' },
        correctAnswer: 'A',
        marks: 1
      };
      
      questions.push({
        question_number: i + 1,
        question: templateQ.question,
        option_a: templateQ.options.A,
        option_b: templateQ.options.B,
        option_c: templateQ.options.C,
        option_d: templateQ.options.D,
        correct_answer: templateQ.correctAnswer,
        marks: templateQ.marks
      });
    }

    return questions;
  } catch (error) {
    console.error('Quiz generation error:', error);
    throw new Error('Failed to generate quiz');
  }
}

// Generate mock exam using mock data
export async function generateMockExam(subject, examLevel, examBoard) {
  try {
    const examTemplates = {
      'Biology': {
        'GCSE': {
          title: 'GCSE Biology Mock Exam - Section A & B',
          totalMarks: 50,
          questions: [
            { number: 1, text: 'Describe the structure and function of mitochondria in plant and animal cells.', type: 'short-answer', marks: 5, sampleAnswer: 'Mitochondria have a double membrane with cristae. They are the site of aerobic respiration producing ATP.' },
            { number: 2, text: 'Explain how enzymes speed up reactions at the molecular level.', type: 'short-answer', marks: 6, sampleAnswer: 'Enzymes lower activation energy by forming enzyme-substrate complexes, allowing reactions to occur faster at lower temperatures.' },
            { number: 3, text: 'Discuss photosynthesis and respiration as complementary processes.', type: 'extended-answer', marks: 9, sampleAnswer: 'Photosynthesis produces glucose and oxygen from CO₂ and water. Respiration uses glucose and oxygen to release energy. The products of one are reactants of the other.' },
          ]
        }
      }
    };

    const template = examTemplates[subject]?.[examLevel] || {
      title: `${examLevel} ${subject} Mock Exam`,
      totalMarks: 50,
      questions: [
        { number: 1, text: `${subject} Question 1: Answer this question`, type: 'short-answer', marks: 5, sampleAnswer: 'Sample answer for question 1.' },
        { number: 2, text: `${subject} Question 2: Answer this extended question`, type: 'extended-answer', marks: 9, sampleAnswer: 'Extended sample answer for question 2.' },
      ]
    };

    return template;
  } catch (error) {
    console.error('Mock exam generation error:', error);
    throw new Error('Failed to generate mock exam');
  }
}
